# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    platform: linux/amd64
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - conductor
    networks:
      - backend
  server:
    hostname: server
    env_file:
      - ../.env
    restart: always
    build:
      context: ..
      dockerfile: build/Dockerfile.server
    networks:
      - backend
  conductor:
    hostname: conductor
    env_file:
      - ../.env
    restart: always
    build:
      context: ..
      dockerfile: build/Dockerfile.conductor
    networks:
      - backend

networks:
  backend:

