name: CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          working-directory: ./backend

    # - name: Test
    #   run: make test